# Generated by Django 2.2.6 on 2019-10-11 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='edescription',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
