# Generated by Django 2.2.6 on 2019-10-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20191011_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department_name',
            field=models.IntegerField(choices=[(0, 'IT-Department'), (1, 'HR-Department')], default=1),
            preserve_default=False,
        ),
    ]
