# Generated by Django 2.2.6 on 2019-10-11 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_employee_department_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department_name',
        ),
    ]
